// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgAJSCeSprFd9HcU09L3SvuTVX4vRQE1U',
    appId: '1:11954727980:web:b046daa7ebbab4f4503589',
    messagingSenderId: '11954727980',
    projectId: 'iotdatabase-5a29c',
    authDomain: 'iotdatabase-5a29c.firebaseapp.com',
    storageBucket: 'iotdatabase-5a29c.firebasestorage.app',
    measurementId: 'G-5424BH7J1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYST9TFH0mV-Lq0OY1yIbMaYNL5ut3HnE',
    appId: '1:11954727980:android:20e835690f3fd5e2503589',
    messagingSenderId: '11954727980',
    projectId: 'iotdatabase-5a29c',
    storageBucket: 'iotdatabase-5a29c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTYuE9rYC1jfs7KD5YqekmC4Rc3rWysoM',
    appId: '1:11954727980:ios:296ae80a869fb08b503589',
    messagingSenderId: '11954727980',
    projectId: 'iotdatabase-5a29c',
    storageBucket: 'iotdatabase-5a29c.firebasestorage.app',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTYuE9rYC1jfs7KD5YqekmC4Rc3rWysoM',
    appId: '1:11954727980:ios:296ae80a869fb08b503589',
    messagingSenderId: '11954727980',
    projectId: 'iotdatabase-5a29c',
    storageBucket: 'iotdatabase-5a29c.firebasestorage.app',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgAJSCeSprFd9HcU09L3SvuTVX4vRQE1U',
    appId: '1:11954727980:web:de38a0acc2b5c3ef503589',
    messagingSenderId: '11954727980',
    projectId: 'iotdatabase-5a29c',
    authDomain: 'iotdatabase-5a29c.firebaseapp.com',
    storageBucket: 'iotdatabase-5a29c.firebasestorage.app',
    measurementId: 'G-FBKNND9V75',
  );

}